import express from 'express';
import Event from '../models/Event.js';
import User from '../models/User.js';

const router = express.Router();

const sampleEvents = [
    {
        title: "National Science Olympiad (NSO) 2026",
        description: "The National Science Olympiad (NSO) is an annual school-level competition designed to identify and nurture future scientists by testing logic and application-based science skills.",
        date: new Date('2026-11-15T10:00:00Z'),
        deadline: new Date('2026-10-15T23:59:59Z'),
        location: "Online / Recognised Schools",
        category: "Academic",
        eligibility: "Class 1 to 12 students",
        prizes: "Medals, Certificates, and Cash Prizes up to ₹50,000",
        applicationLink: "https://sofworld.org/nso",
        ageGroup: "Class 1-12",
        registrationFee: "₹150",
        mode: "Offline",
        contactInfo: "info@sofworld.org",
        tags: ["Science", "Olympiad", "National"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "International Mathematics Olympiad (IMO) 2026",
        description: "IMO is a competition to test the mathematical ability and potential of students. It identifies talent and provides a platform for students to compete at international levels.",
        date: new Date('2026-12-05T09:00:00Z'),
        deadline: new Date('2026-11-05T23:59:59Z'),
        location: "Online / Recognised Schools",
        category: "Academic",
        eligibility: "Class 1 to 12 students",
        prizes: "International Medals, Cash Prizes, and Merit Certificates",
        applicationLink: "https://sofworld.org/imo",
        ageGroup: "Class 1-12",
        registrationFee: "₹150",
        mode: "Offline",
        contactInfo: "info@sofworld.org",
        tags: ["Mathematics", "Olympiad", "International"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "TCS iON IntelliGem 2026",
        description: "A national-level contest across India on 21st-century skills like Financial Literacy, Digital Literacy, Global Citizenship, and more.",
        date: new Date('2026-10-20T11:00:00Z'),
        deadline: new Date('2026-09-15T23:59:59Z'),
        location: "Online",
        category: "Skills",
        eligibility: "Class 5 to 9 students",
        prizes: "Cash Prizes, Tablets, Medals, and Certifications",
        applicationLink: "https://learning.tcsionhub.in/hub/intelligem/",
        ageGroup: "Class 5-9",
        registrationFee: "₹500",
        mode: "Online",
        contactInfo: "intelligem@tcs.com",
        tags: ["Skills", "Digital Literacy", "National"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Vidyarthi Vigyan Manthan (VVM) 2026",
        description: "VVM is a national program for educating and popularizing science among school students of VI to XI standards.",
        date: new Date('2026-11-29T10:00:00Z'),
        deadline: new Date('2026-10-31T23:59:59Z'),
        location: "Online",
        category: "Academic",
        eligibility: "Class 6 to 11 students",
        prizes: "National and Zonal level Awards, Mentorship support",
        applicationLink: "https://vvm.org.in/",
        ageGroup: "Class 6-11",
        registrationFee: "₹200",
        mode: "Online",
        contactInfo: "vvm@vijnanabharati.org",
        tags: ["Science", "National", "Research"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1564325724739-bae0bd08762c?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Technovation Girls Challenge 2026",
        description: "Technovation Girls equips young women (ages 8-18) to become tech entrepreneurs and leaders. With the support of volunteer mentors and parents, girls work in teams to code mobile apps that address real-world problems.",
        date: new Date('2026-05-15T14:00:00Z'),
        deadline: new Date('2026-03-12T23:59:59Z'),
        location: "Online / Global",
        category: "Tech",
        eligibility: "Girls ages 8 to 18",
        prizes: "$10,000 Global Winners Prize, Regional Awards",
        applicationLink: "https://www.technovation.org/",
        ageGroup: "Ages 8-18",
        registrationFee: "Free",
        mode: "Online",
        contactInfo: "support@technovation.org",
        tags: ["Tech", "Coding", "Girls", "International"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "NASA Space Apps Challenge 2026",
        description: "The largest global hackathon on Earth. Join thousands of citizens to build open-source solutions to address real-world challenges on Earth and in space.",
        date: new Date('2026-10-05T09:00:00Z'),
        deadline: new Date('2026-09-30T23:59:59Z'),
        location: "Online / Local Hubs",
        category: "Tech",
        eligibility: "Open to all students",
        prizes: "Global Recognition, Visit to NASA Rocket Launch",
        applicationLink: "https://www.spaceappschallenge.org/",
        ageGroup: "All Ages",
        registrationFee: "Free",
        mode: "Hybrid",
        contactInfo: "info@spaceappschallenge.org",
        tags: ["Hackathon", "NASA", "Space", "Tech"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Spell Bee International 2026",
        description: "A unique competition to test spelling, vocabulary, and grammar skills. Improves language proficiency and confidence in students.",
        date: new Date('2026-11-20T10:00:00Z'),
        deadline: new Date('2026-10-25T23:59:59Z'),
        location: "Online / Schools",
        category: "Academic",
        eligibility: "Class 1 to 12 students",
        prizes: "Cash Awards, Gold, Silver & Bronze Medals",
        applicationLink: "https://spellbeeinternational.com/",
        ageGroup: "Class 1-12",
        registrationFee: "₹300",
        mode: "Online",
        contactInfo: "contact@spellbeeinternational.com",
        tags: ["English", "Spell Bee", "National"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "National Talent Search Examination (NTSE)",
        description: "One of the most prestigious scholarship programs in India, aimed at identifying and recognizing students with high intellect and academic talent.",
        date: new Date('2026-11-08T09:30:00Z'),
        deadline: new Date('2026-09-30T23:59:59Z'),
        location: "Designated Exam Centers",
        category: "Academic",
        eligibility: "Class 10 students",
        prizes: "Monthly Scholarship until Ph.D level",
        applicationLink: "https://ncert.nic.in/national-talent-examination.php",
        ageGroup: "Class 10",
        registrationFee: "Free",
        mode: "Offline",
        contactInfo: "ntsexam.ncert@gov.in",
        tags: ["NTSE", "Scholarship", "Government"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Zonal Informatics Olympiad (ZIO) 2026",
        description: "The first level of selection for the Indian team for the International Olympiad in Informatics (IOI). Testing algorithmic and logical thinking.",
        date: new Date('2026-12-15T10:00:00Z'),
        deadline: new Date('2026-11-25T23:59:59Z'),
        location: "Online Center Proctored",
        category: "Tech",
        eligibility: "School students below Class 12",
        prizes: "Qualify for INOI, National certificates",
        applicationLink: "https://www.iarcs.org.in/",
        ageGroup: "Below Class 12",
        registrationFee: "₹400",
        mode: "Offline",
        contactInfo: "info@iarcs.org.in",
        tags: ["Coding", "CS", "Olympiad"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "YUVIKA - ISRO Young Scientist Program 2026",
        description: "YUVIKA stands for 'YUva VIgyani KAryakram', a special program for School Children, to impart basic knowledge on Space Technology, Space Science and Space Applications.",
        date: new Date('2026-05-10T09:00:00Z'),
        deadline: new Date('2026-03-31T23:59:59Z'),
        location: "ISRO Centers",
        category: "Science",
        eligibility: "Class 9 students",
        prizes: "Fully funded stay and training at ISRO centers",
        applicationLink: "https://yuvika.isro.gov.in/",
        ageGroup: "Class 9",
        registrationFee: "Free",
        mode: "Offline",
        contactInfo: "yuvika@isro.gov.in",
        tags: ["ISRO", "Space", "Science", "National"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1614728263952-84ea256f9679?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "FIT India Quiz 2026",
        description: "A national-level quiz on fitness and sports. Participants from across the country compete to win prizes for themselves and their schools.",
        date: new Date('2026-10-25T11:00:00Z'),
        deadline: new Date('2026-09-20T23:59:59Z'),
        location: "Online",
        category: "Quiz",
        eligibility: "Class 1 to 12 students",
        prizes: "₹3.25 Crore Total Prize Pool for Students & Schools",
        applicationLink: "https://fitindia.gov.in/quiz",
        ageGroup: "Class 1-12",
        registrationFee: "Free",
        mode: "Online",
        contactInfo: "fitindia@gov.in",
        tags: ["Fitness", "Sports", "Quiz", "National"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Aryabhata Ganit Challenge 2026",
        description: "An initiative by CBSE to promote interest in Mathematics and its applications in daily life among students.",
        date: new Date('2026-11-12T10:00:00Z'),
        deadline: new Date('2026-10-15T23:59:59Z'),
        location: "Online (CBSE Schools)",
        category: "Academic",
        eligibility: "Class 8 to 10 students",
        prizes: "Top 100 students from each CBSE region get certificates",
        applicationLink: "https://cbseacademic.nic.in/",
        ageGroup: "Class 8-10",
        registrationFee: "Free",
        mode: "Online",
        contactInfo: "cbse@nic.in",
        tags: ["Mathematics", "CBSE", "Challenge"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Young Artiste National Arts Music & Dance",
        description: "India's largest national-level platform for the performing arts for children, focused on recognizing young talent in Music and Dance.",
        date: new Date('2026-06-20T10:00:00Z'),
        deadline: new Date('2026-05-15T23:59:59Z'),
        location: "Regional Centers / Final in Bangalore",
        category: "Arts",
        eligibility: "Ages 11 to 18",
        prizes: "₹1 Crore Total Scholarship Pool, Mentorship",
        applicationLink: "https://www.youngartiste.com/",
        ageGroup: "Ages 11-18",
        registrationFee: "₹200",
        mode: "Hybrid",
        contactInfo: "info@youngartiste.com",
        tags: ["Arts", "Music", "Dance", "National"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1547153760-18fc86024957?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "International Physics Olympiad (IPhO) Selection",
        description: "The national standard examination in Physics (NSEP) is the first step towards representing India in the International Physics Olympiad.",
        date: new Date('2026-11-22T10:00:00Z'),
        deadline: new Date('2026-10-20T23:59:59Z'),
        location: "Exam Centers All India",
        category: "Academic",
        eligibility: "Class 11 & 12 (Science stream)",
        prizes: "Medals, Certificates, Opportunity for OCSC Training",
        applicationLink: "https://iapt.org.in/",
        ageGroup: "Class 11-12",
        registrationFee: "₹200",
        mode: "Offline",
        contactInfo: "iapt@iapt.org.in",
        tags: ["Physics", "National", "Olympiad"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1636466497217-39a814085141?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "National Level Photography Contest 2026",
        description: "Showcase your photography skills through this inter-school competition. Theme: 'Incredible India through a Student's Lens'.",
        date: new Date('2026-08-15T12:00:00Z'),
        deadline: new Date('2026-07-31T23:59:59Z'),
        location: "Online Submission",
        category: "Photography",
        eligibility: "Class 9 to 12 students",
        prizes: "Professional Camera Gear, Cash Prizes and Exhibition",
        applicationLink: "https://apnaevents.in/contest/photography",
        ageGroup: "Class 9-12",
        registrationFee: "Free",
        mode: "Online",
        contactInfo: "contests@apnaevents.in",
        tags: ["Photography", "Inter-school", "Arts"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Unified International Mathematics Olympiad (UIMO)",
        description: "UIMO is a curriculum-based strategy to test students' mathematical ability and potential.",
        date: new Date('2026-12-10T11:00:00Z'),
        deadline: new Date('2026-11-10T23:59:59Z'),
        location: "Online / Recognised Schools",
        category: "Academic",
        eligibility: "Class 1 to 12 students",
        prizes: "Top 3 get Tablets, Laptop, Medals & Cash Prizes",
        applicationLink: "https://www.unifiedcouncil.com/uimo.html",
        ageGroup: "Class 1-12",
        registrationFee: "₹150",
        mode: "Online",
        contactInfo: "admin@unifiedcouncil.com",
        tags: ["Mathematics", "UIMO", "National"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "National English Olympiad (NEO) 2026",
        description: "Evaluating students' English language and punctuation skills through a structured national exam.",
        date: new Date('2026-11-28T10:00:00Z'),
        deadline: new Date('2026-10-31T23:59:59Z'),
        location: "Online / Local Schools",
        category: "Academic",
        eligibility: "Class 1 to 12 students",
        prizes: "Cash Prizes, Merit Certificates, and School level awards",
        applicationLink: "https://sofworld.org/ieo",
        ageGroup: "Class 1-12",
        registrationFee: "₹150",
        mode: "Offline",
        contactInfo: "info@sofworld.org",
        tags: ["English", "Olympiad", "National"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "All India Schools Quiz Competition 2026",
        description: "The ultimate quiz battle for school students. Topics include Mythology, History, Science, Sports, and Current Affairs.",
        date: new Date('2026-11-14T09:00:00Z'),
        deadline: new Date('2026-10-14T23:59:59Z'),
        location: "Online Prelims / Final in Kolkata",
        category: "Quiz",
        eligibility: "School teams (Class 9-12)",
        prizes: "₹5 Lakh Total Prize Pool, Fully Funded travel for finals",
        applicationLink: "https://apnaevents.in/quiz/all-india-school",
        ageGroup: "Class 9-12",
        registrationFee: "₹500 per team",
        mode: "Hybrid",
        contactInfo: "quiz@apnaevents.in",
        tags: ["Quiz", "Team", "General Knowledge"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "National Cyber Olympiad (NCO) 2026",
        description: "Focusing on the IT and Computer knowledge of students. Tests awareness of the latest in Cyber space and IT security.",
        date: new Date('2026-12-18T10:00:00Z'),
        deadline: new Date('2026-11-20T23:59:59Z'),
        location: "Online / Schools",
        category: "Tech",
        eligibility: "Class 1 to 12 students",
        prizes: "Medals, Merit certificates and scholarships",
        applicationLink: "https://sofworld.org/nco",
        ageGroup: "Class 1-12",
        registrationFee: "₹150",
        mode: "Offline",
        contactInfo: "info@sofworld.org",
        tags: ["Cyber", "IT", "Tech", "Olympiad"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "The Hindu School Debate Competition 2026",
        description: "A prestigious debate competition for students, foster critical thinking and articulation skills.",
        date: new Date('2026-09-05T10:30:00Z'),
        deadline: new Date('2026-08-15T23:59:59Z'),
        location: "Major Metro Cities",
        category: "Public Speaking",
        eligibility: "Class 10 to 12 students",
        prizes: "Best Speaker Award, Internship with The Hindu",
        applicationLink: "https://thehindu.com/debate",
        ageGroup: "Class 10-12",
        registrationFee: "Free",
        mode: "Offline",
        contactInfo: "debate@thehindu.co.in",
        tags: ["Debate", "Public Speaking", "National"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "ASSET Talent Search 2026",
        description: "ASSET Talent Search (ATS) is a prestigious talent discovery program that identifies gifted students from classes 5 to 9.",
        date: new Date('2026-12-12T09:00:00Z'),
        deadline: new Date('2026-11-20T23:59:59Z'),
        location: "Online Proctored / Test Centers",
        category: "Academic",
        eligibility: "Class 5 to 9 students in 85th percentile of ASSET",
        prizes: "Admission to exclusive summer programs in US/Europe",
        applicationLink: "https://www.assettalentsearch.com/",
        ageGroup: "Class 5-9",
        registrationFee: "₹3500",
        mode: "Online",
        contactInfo: "ats@ei-india.com",
        tags: ["Talent Search", "International", "Programs"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Inter-School Chess Championship 2026",
        description: "Show off your strategic moves at our All India School Chess Championship. Organized in association with National Chess Federation.",
        date: new Date('2026-07-10T10:00:00Z'),
        deadline: new Date('2026-06-25T23:59:59Z'),
        location: "Online (Finals Offline in Chennai)",
        category: "Sports",
        eligibility: "Class 5 to 12 students",
        prizes: "Grandmaster Training session for Winners, Cash Prizes",
        applicationLink: "https://apnaevents.in/sports/chess",
        ageGroup: "Class 5-12",
        registrationFee: "₹300",
        mode: "Hybrid",
        contactInfo: "sports@apnaevents.in",
        tags: ["Chess", "Sports", "Strategic"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Aryabhata Inter-School Math Competition",
        description: "Celebrating the legacy of the great mathematician through a challenging problem-solving fest.",
        date: new Date('2026-12-22T09:30:00Z'),
        deadline: new Date('2026-12-10T23:59:59Z'),
        location: "New Delhi",
        category: "Academic",
        eligibility: "Class 11 & 12 students",
        prizes: "Legacy Trophy, Scholarship for higher studies",
        applicationLink: "https://apnaevents.in/maths/aryabhata",
        ageGroup: "Class 11-12",
        registrationFee: "₹250",
        mode: "Offline",
        contactInfo: "aryabhata@mathsindia.org",
        tags: ["Mathematics", "Legend", "Inter-school"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "National Geography Olympiad (NGO) 2026",
        description: "Checking students' understanding of physical and political geography, environmental issues and sustainability.",
        date: new Date('2026-11-30T10:00:00Z'),
        deadline: new Date('2026-10-31T23:59:59Z'),
        location: "Online",
        category: "Academic",
        eligibility: "Class 5 to 12 students",
        prizes: "Opportunity to represent India in iGeo (International Geography Olympiad)",
        applicationLink: "https://www.geographyolympiad.org/",
        ageGroup: "Class 5-12",
        registrationFee: "₹500",
        mode: "Online",
        contactInfo: "info@geographyolympiad.org",
        tags: ["Geography", "Environmental", "National"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "Young Historian Essay Contest 2026",
        description: "Writing about the unsung heroes of India's independence movement. Focus on historical research and storytelling.",
        date: new Date('2026-08-10T14:00:00Z'),
        deadline: new Date('2026-07-20T23:59:59Z'),
        location: "Online Page Submission",
        category: "History",
        eligibility: "Class 9 to 12 students",
        prizes: "Merit Badge, Publication in National History Journal",
        applicationLink: "https://apnaevents.in/contest/history",
        ageGroup: "Class 9-12",
        registrationFee: "Free",
        mode: "Online",
        contactInfo: "history@apnaevents.in",
        tags: ["History", "Essay", "Research"],
        featured: false,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1447069387593-a5de0862481e?auto=format&fit=crop&q=80&w=1200",
        verified: true
    },
    {
        title: "School Innovation Challenge by NITI Aayog",
        description: "A flagship initiative to promote entrepreneurship and innovation at school level. Part of Atal Innovation Mission.",
        date: new Date('2026-10-30T10:00:00Z'),
        deadline: new Date('2026-09-30T23:59:59Z'),
        location: "Online / Tinkering Labs",
        category: "Innovation",
        eligibility: "Schools with Atal Tinkering Labs",
        prizes: "Grant for School Lab, Certification for Student Teams",
        applicationLink: "https://aim.gov.in/",
        ageGroup: "Class 6-12",
        registrationFee: "Free",
        mode: "Hybrid",
        contactInfo: "aim-niti@nic.in",
        tags: ["Innovation", "Entrepreneurship", "Government"],
        featured: true,
        status: "upcoming",
        image: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=1200",
        verified: true
    }
];

router.post('/add-sample-events', async (req, res) => {
    try {
        console.log('🚀 Adding 30+ real events to production...');
        const adminUser = await User.findOne({ email: 'aadarshgolucky@gmail.com' });

        if (!adminUser) {
            return res.status(404).json({ success: false, message: 'Admin user not found.' });
        }

        // Optionally clear current events (Commented for safety)
        // await Event.deleteMany({});

        const eventsToAdd = sampleEvents.map(event => ({
            ...event,
            organizer: adminUser._id
        }));

        const result = await Event.insertMany(eventsToAdd);
        console.log(`✅ Successfully added ${result.length} events!`);

        res.status(201).json({
            success: true,
            message: `Successfully added ${result.length} real events to the database`,
            count: result.length
        });
    } catch (error) {
        console.error('❌ Error adding events:', error.message);
        res.status(500).json({ success: false, message: error.message });
    }
});

export default router;
